#!/usr/bin/env node
/**
 * download-assets.js — P0.6
 *
 * Downloads all game assets (images + audio) from the original CDN
 * (www.nvhae.com/starcraft) into the local img/ and bgm/ folders so the
 * game is fully self-contained and no longer depends on the black-box CDN.
 *
 * The asset list is generated by grepping every `Game.CDN+"..."` reference in
 * the codebase, so it always matches what the game actually loads.
 *
 * Usage:  node tools/download-assets.js
 * Idempotent: skips files that already exist and are non-empty.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const http = require('http');

const CDN = 'http://www.nvhae.com/starcraft';
const ROOT = path.join(__dirname, '..');

// ---- Build the asset manifest from the codebase --------------------------
function collectRefs() {
  const files = [];
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === 'node_modules' || entry.name === '.git') continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith('.js')) files.push(full);
    }
  };
  walk(ROOT);

  const assets = new Set();
  const re = /Game\.CDN\s*\+\s*["']([^"']+)["']/g;
  for (const f of files) {
    const src = fs.readFileSync(f, 'utf8');
    let m;
    while ((m = re.exec(src)) !== null) assets.add(m[1]);
  }
  return Array.from(assets).sort();
}

// ---- Download one asset (with retry) ------------------------------------
function fetchOnce(url, dest, attempt = 0) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const req = http.get({
      hostname: u.hostname,
      port: u.port || 80,
      path: u.pathname + u.search,
      headers: { 'User-Agent': 'Mozilla/5.0 (StarCraft-AI asset fetch)', 'Accept': '*/*' }
    }, (res) => {
      if (res.statusCode === 200) {
        const chunks = [];
        res.on('data', (c) => chunks.push(c));
        res.on('end', () => {
          const buf = Buffer.concat(chunks);
          fs.mkdirSync(path.dirname(dest), { recursive: true });
          fs.writeFileSync(dest, buf);
          resolve({ size: buf.length });
        });
      } else {
        res.resume();
        reject(new Error(`HTTP ${res.statusCode} for ${url}`));
      }
    });
    req.on('error', reject);
    req.setTimeout(30000, () => req.destroy(new Error('timeout')));
  });
}

async function download(url, dest) {
  // Skip if already present and non-empty
  if (fs.existsSync(dest) && fs.statSync(dest).size > 0) {
    return { skipped: true, size: fs.statSync(dest).size };
  }
  for (let attempt = 0; attempt < 7; attempt++) {
    try {
      return await fetchOnce(url, dest, attempt);
    } catch (e) {
      if (attempt === 6) throw e;
      // Exponential backoff — the CDN resets connections under load.
      await new Promise((r) => setTimeout(r, 500 * (attempt + 1)));
    }
  }
}

// ---- Main ----------------------------------------------------------------
(async () => {
  const assets = collectRefs();
  console.log(`Found ${assets.length} asset references.`);
  const imgs = assets.filter((a) => a.startsWith('img/'));
  const auds = assets.filter((a) => a.startsWith('bgm/'));
  console.log(`  images: ${imgs.length}, audio: ${auds.length}`);

  let ok = 0, skipped = 0, failed = 0;
  const failures = [];

  // Download SEQUENTIALLY with a small inter-request delay. The CDN
  // (www.nvhae.com) resets connections under concurrent load, so a polite
  // serial stream is far more reliable than a concurrency pool.
  let i = 0;
  async function worker() {
    while (i < assets.length) {
      const rel = assets[i++];
      const dest = path.join(ROOT, rel);
      try {
        const r = await download(CDN + '/' + rel, dest);
        if (r.skipped) { skipped++; }
        else { ok++; console.log(`  + ${rel} (${r.size} bytes)`); }
      } catch (e) {
        failed++;
        failures.push(rel);
        console.log(`  ! ${rel}: ${e.message}`);
      }
      // Be gentle: small pause between requests.
      await new Promise((r) => setTimeout(r, 150));
    }
  }
  await Promise.all(Array.from({ length: 1 }, worker));

  console.log(`\nDone. downloaded=${ok} skipped=${skipped} failed=${failed}`);
  if (failures.length) {
    console.log('Failed assets:');
    failures.forEach((f) => console.log('  ' + f));
    process.exitCode = 1;
  }
})();
